"""Add Contract and ContractComment models

Revision ID: 0e7ee8007a91
Revises: aea4038c8801
Create Date: 2026-02-26 10:06:36.749210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0e7ee8007a91'
down_revision: Union[str, Sequence[str], None] = 'aea4038c8801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tracked_link_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expiry_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contract_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('to_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('signature_data', sa.Text(), nullable=True),
    sa.Column('client_signature_data', sa.Text(), nullable=True),
    sa.Column('signer_ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('signer_user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_tracked_link_token'), 'contracts', ['tracked_link_token'], unique=True)
    op.create_index(op.f('ix_contracts_user_id'), 'contracts', ['user_id'], unique=False)
    op.create_table('contract_comments',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contract_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_comments_author_id'), 'contract_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_contract_comments_contract_id'), 'contract_comments', ['contract_id'], unique=False)
    op.add_column('invoices', sa.Column('contract_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('invoices', sa.Column('signature_data', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('client_signature_data', sa.Text(), nullable=True))
    op.create_index(op.f('ix_invoices_contract_id'), 'invoices', ['contract_id'], unique=False)
    op.create_foreign_key(None, 'invoices', 'contracts', ['contract_id'], ['id'])
    op.add_column('quotes', sa.Column('contract_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('quotes', sa.Column('signature_data', sa.Text(), nullable=True))
    op.add_column('quotes', sa.Column('client_signature_data', sa.Text(), nullable=True))
    op.create_index(op.f('ix_quotes_contract_id'), 'quotes', ['contract_id'], unique=False)
    op.create_foreign_key(None, 'quotes', 'contracts', ['contract_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quotes', type_='foreignkey')
    op.drop_index(op.f('ix_quotes_contract_id'), table_name='quotes')
    op.drop_column('quotes', 'client_signature_data')
    op.drop_column('quotes', 'signature_data')
    op.drop_column('quotes', 'contract_id')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_contract_id'), table_name='invoices')
    op.drop_column('invoices', 'client_signature_data')
    op.drop_column('invoices', 'signature_data')
    op.drop_column('invoices', 'contract_id')
    op.drop_index(op.f('ix_contract_comments_contract_id'), table_name='contract_comments')
    op.drop_index(op.f('ix_contract_comments_author_id'), table_name='contract_comments')
    op.drop_table('contract_comments')
    op.drop_index(op.f('ix_contracts_user_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_tracked_link_token'), table_name='contracts')
    op.drop_table('contracts')
    # ### end Alembic commands ###
