"""V8 Quote Polish

Revision ID: 510232e171d8
Revises: 
Create Date: 2026-02-28 01:47:31.517964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '510232e171d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('extraction_logs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('items_extracted', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_logs_created_at'), 'extraction_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_extraction_logs_user_id'), 'extraction_logs', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stripe_customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plan', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subscription_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('invoices_this_month', sa.Integer(), nullable=False),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('logo_base64', sa.Text(), nullable=True),
    sa.Column('signature_base64', sa.Text(), nullable=True),
    sa.Column('tax_region', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('business_profiles',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('signature_data', sa.Text(), nullable=True),
    sa.Column('primary_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_currency_symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_notes', sa.Text(), nullable=True),
    sa.Column('watermark_enabled', sa.Boolean(), nullable=False),
    sa.Column('watermark_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('watermark_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('watermark_image', sa.Text(), nullable=True),
    sa.Column('watermark_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('watermark_opacity', sa.Float(), nullable=False),
    sa.Column('watermark_rotation', sa.Float(), nullable=False),
    sa.Column('watermark_font_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_profiles_user_id'), 'business_profiles', ['user_id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('admin_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('registration_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logo_base64', sa.Text(), nullable=True),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_admin_user_id'), 'companies', ['admin_user_id'], unique=False)
    op.create_table('relationships',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('initiator_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recipient_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('billing_rate', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('billing_cycle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['initiator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationships_initiator_id'), 'relationships', ['initiator_id'], unique=False)
    op.create_index(op.f('ix_relationships_recipient_id'), 'relationships', ['recipient_id'], unique=False)
    op.create_table('saved_clients',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_clients_user_id'), 'saved_clients', ['user_id'], unique=False)
    op.create_table('tax_ledgers',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tax_year', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_earned', sa.Float(), nullable=False),
    sa.Column('total_tax_collected', sa.Float(), nullable=False),
    sa.Column('q1_q4_json', sa.JSON(), nullable=True),
    sa.Column('per_relationship_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_ledgers_user_id'), 'tax_ledgers', ['user_id'], unique=False)
    op.create_table('trust_profiles',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('invoice_accuracy', sa.Float(), nullable=False),
    sa.Column('on_time_rate', sa.Float(), nullable=False),
    sa.Column('avg_response_hours', sa.Float(), nullable=False),
    sa.Column('dispute_rate', sa.Float(), nullable=False),
    sa.Column('avg_relationship_days', sa.Float(), nullable=False),
    sa.Column('total_engagements', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trust_profiles_user_id'), 'trust_profiles', ['user_id'], unique=True)
    op.create_table('contracts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relationship_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tracked_link_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expiry_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contract_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('to_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('signature_data', sa.Text(), nullable=True),
    sa.Column('client_signature_data', sa.Text(), nullable=True),
    sa.Column('signer_ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('signer_user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationships.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_relationship_id'), 'contracts', ['relationship_id'], unique=False)
    op.create_index(op.f('ix_contracts_tracked_link_token'), 'contracts', ['tracked_link_token'], unique=True)
    op.create_index(op.f('ix_contracts_user_id'), 'contracts', ['user_id'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relationship_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('issuer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recipient_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quote_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quote_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('currency_symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('from_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('from_details', sa.Text(), nullable=True),
    sa.Column('to_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('to_details', sa.Text(), nullable=True),
    sa.Column('line_items_json', sa.JSON(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('tax_total', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('timeline', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('primary_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('signature_data', sa.Text(), nullable=True),
    sa.Column('client_signature_data', sa.Text(), nullable=True),
    sa.Column('pdf_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tracked_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tracked_link_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extracted_json', sa.JSON(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issuer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationships.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_issuer_id'), 'quotes', ['issuer_id'], unique=False)
    op.create_index(op.f('ix_quotes_recipient_id'), 'quotes', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_quotes_relationship_id'), 'quotes', ['relationship_id'], unique=False)
    op.create_index(op.f('ix_quotes_tracked_token'), 'quotes', ['tracked_token'], unique=True)
    op.create_index(op.f('ix_quotes_user_id'), 'quotes', ['user_id'], unique=False)
    op.create_table('contract_comments',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contract_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_comments_author_id'), 'contract_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_contract_comments_contract_id'), 'contract_comments', ['contract_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relationship_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('issuer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recipient_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quote_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('invoice_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('invoice_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('currency_symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('from_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('from_details', sa.Text(), nullable=True),
    sa.Column('to_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('to_details', sa.Text(), nullable=True),
    sa.Column('line_items_json', sa.JSON(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('tax_total', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('due_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('primary_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('signature_data', sa.Text(), nullable=True),
    sa.Column('client_signature_data', sa.Text(), nullable=True),
    sa.Column('pdf_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tracked_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('accessed_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issuer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationships.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_issuer_id'), 'invoices', ['issuer_id'], unique=False)
    op.create_index(op.f('ix_invoices_quote_id'), 'invoices', ['quote_id'], unique=False)
    op.create_index(op.f('ix_invoices_recipient_id'), 'invoices', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_invoices_relationship_id'), 'invoices', ['relationship_id'], unique=False)
    op.create_index(op.f('ix_invoices_tracked_token'), 'invoices', ['tracked_token'], unique=True)
    op.create_index(op.f('ix_invoices_user_id'), 'invoices', ['user_id'], unique=False)
    op.create_table('quote_comments',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quote_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_comments_author_id'), 'quote_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_quote_comments_quote_id'), 'quote_comments', ['quote_id'], unique=False)
    op.create_table('quote_line_items',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quote_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_line_items_quote_id'), 'quote_line_items', ['quote_id'], unique=False)
    op.create_table('invoice_comments',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('invoice_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_comments_author_id'), 'invoice_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_invoice_comments_invoice_id'), 'invoice_comments', ['invoice_id'], unique=False)
    op.create_table('invoice_line_items',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('invoice_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_line_items_invoice_id'), 'invoice_line_items', ['invoice_id'], unique=False)
    op.create_table('payment_records',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('invoice_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relationship_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('method_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_records_invoice_id'), 'payment_records', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payment_records_relationship_id'), 'payment_records', ['relationship_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_records_relationship_id'), table_name='payment_records')
    op.drop_index(op.f('ix_payment_records_invoice_id'), table_name='payment_records')
    op.drop_table('payment_records')
    op.drop_index(op.f('ix_invoice_line_items_invoice_id'), table_name='invoice_line_items')
    op.drop_table('invoice_line_items')
    op.drop_index(op.f('ix_invoice_comments_invoice_id'), table_name='invoice_comments')
    op.drop_index(op.f('ix_invoice_comments_author_id'), table_name='invoice_comments')
    op.drop_table('invoice_comments')
    op.drop_index(op.f('ix_quote_line_items_quote_id'), table_name='quote_line_items')
    op.drop_table('quote_line_items')
    op.drop_index(op.f('ix_quote_comments_quote_id'), table_name='quote_comments')
    op.drop_index(op.f('ix_quote_comments_author_id'), table_name='quote_comments')
    op.drop_table('quote_comments')
    op.drop_index(op.f('ix_invoices_user_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_tracked_token'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_relationship_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_recipient_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_quote_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_issuer_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_contract_comments_contract_id'), table_name='contract_comments')
    op.drop_index(op.f('ix_contract_comments_author_id'), table_name='contract_comments')
    op.drop_table('contract_comments')
    op.drop_index(op.f('ix_quotes_user_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_tracked_token'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_relationship_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_recipient_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_issuer_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_contracts_user_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_tracked_link_token'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_relationship_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_trust_profiles_user_id'), table_name='trust_profiles')
    op.drop_table('trust_profiles')
    op.drop_index(op.f('ix_tax_ledgers_user_id'), table_name='tax_ledgers')
    op.drop_table('tax_ledgers')
    op.drop_index(op.f('ix_saved_clients_user_id'), table_name='saved_clients')
    op.drop_table('saved_clients')
    op.drop_index(op.f('ix_relationships_recipient_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_initiator_id'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_companies_admin_user_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_business_profiles_user_id'), table_name='business_profiles')
    op.drop_table('business_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_extraction_logs_user_id'), table_name='extraction_logs')
    op.drop_index(op.f('ix_extraction_logs_created_at'), table_name='extraction_logs')
    op.drop_table('extraction_logs')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
