"""Add new Phase 5 6 7 columns and tables

Revision ID: 956368f9ce8c
Revises: 
Create Date: 2026-02-25 22:52:10.932959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '956368f9ce8c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_profiles', sa.Column('business_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('business_profiles', sa.Column('payment_terms', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('business_profiles', sa.Column('tax_region', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('business_profiles', sa.Column('vat_registered', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('invoices', sa.Column('quote_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('invoices', sa.Column('extracted_json', sa.JSON(), nullable=True))
    op.add_column('invoices', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), server_default='draft', nullable=False))
    op.add_column('invoices', sa.Column('tracked_link_token', sqlmodel.sql.sqltypes.AutoString(), server_default='', nullable=False))
    op.add_column('invoices', sa.Column('sent_at', sa.DateTime(), nullable=True))
    op.add_column('invoices', sa.Column('viewed_at', sa.DateTime(), nullable=True))
    op.add_column('invoices', sa.Column('paid_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_invoices_quote_id'), 'invoices', ['quote_id'], unique=False)
    op.create_foreign_key(None, 'invoices', 'quotes', ['quote_id'], ['id'])
    op.add_column('users', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), server_default='freelancer', nullable=False))
    op.alter_column('users', 'login_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'total_extractions',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'total_voice_inputs',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_column('users', 'country_code')
    op.drop_column('users', 'country_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('country_code', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.alter_column('users', 'total_voice_inputs',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'total_extractions',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'login_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_quote_id'), table_name='invoices')
    op.drop_column('invoices', 'paid_at')
    op.drop_column('invoices', 'viewed_at')
    op.drop_column('invoices', 'sent_at')
    op.drop_column('invoices', 'tracked_link_token')
    op.drop_column('invoices', 'status')
    op.drop_column('invoices', 'extracted_json')
    op.drop_column('invoices', 'quote_id')
    op.drop_column('business_profiles', 'vat_registered')
    op.drop_column('business_profiles', 'tax_region')
    op.drop_column('business_profiles', 'payment_terms')
    op.drop_column('business_profiles', 'business_name')
    # ### end Alembic commands ###
