"""add author_name to comments

Revision ID: aea4038c8801
Revises: 7f8a31f7cfe8
Create Date: 2026-02-25 23:53:57.006703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aea4038c8801'
down_revision: Union[str, Sequence[str], None] = '7f8a31f7cfe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_comments', sa.Column('author_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('quote_comments', sa.Column('author_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote_comments', 'author_name')
    op.drop_column('invoice_comments', 'author_name')
    # ### end Alembic commands ###
